#!/usr/bin/env python3

# script arguments: signature

import sys

from pymacaroons import Macaroon


def main(argv):
    serialized = argv[0]

    m = Macaroon.deserialize(serialized)
    print(m.signature)
    exit(0)

if __name__ == "__main__":
    main(sys.argv[1:])
