#!/usr/bin/env python3

# script arguments: location key id caveat_id

import sys

from pymacaroons import Macaroon


def main(argv):
    location = argv[0]
    key = argv[1]
    id = argv[2]
    caveat_id = argv[3]

    m = Macaroon(location=location, key=key, identifier=id)
    m.add_first_party_caveat(caveat_id)
    print(m.serialize())
    print(key)
    print(caveat_id)
    exit(0)

if __name__ == "__main__":
    main(sys.argv[1:])
