#!/usr/bin/env python3

# script arguments: serialized_macaroon discharge_macaroon key
#                   first_party_caveat discharge_first_party

import sys

from pymacaroons import Macaroon, Verifier


def main(argv):
    serialized_macaroon = argv[0]
    discharge_macaroon = argv[1]
    key = argv[2]
    first_party_caveat = argv[3]
    discharge_first_party = argv[4]

    macaroon = Macaroon.deserialize(serialized_macaroon)
    bound_discharge = Macaroon.deserialize(discharge_macaroon)

    verifier = Verifier()
    verifier.satisfy_exact(first_party_caveat)
    verifier.satisfy_exact(discharge_first_party)

    try:
        print(verifier.verify(macaroon, key, discharge_macaroons=[bound_discharge]))
    except Exception as e:
        print("False")

    exit(0)

if __name__ == "__main__":
    main(sys.argv[1:])
