#!/usr/bin/env python3

# script arguments: location key id

import sys

from pymacaroons import Macaroon


def main(argv):
    location = argv[0]
    key = argv[1]
    id = argv[2]

    m = Macaroon(location=location, key=key, identifier=id)
    print(m.signature)
    exit(0)

if __name__ == "__main__":
    main(sys.argv[1:])
