#!/usr/bin/env python

# script arguments: location key id

import sys

import macaroons


def main(argv):
    location = argv[0]
    key = argv[1]
    id = argv[2]

    m = macaroons.create(location, key, id)
    print m.signature
    exit(0)

if __name__ == "__main__":
    main(sys.argv[1:])
