#!/usr/bin/env python

# script arguments: serialized

import sys

import macaroons


def main(argv):
    serialized = argv[0]

    m = macaroons.deserialize(serialized)

    print m.signature
    exit(0)

if __name__ == "__main__":
    main(sys.argv[1:])
