#!/usr/bin/env python

# script arguments: serialized key first_party_caveat

import sys

import macaroons


def main(argv):
    serialized = argv[0]
    key = argv[1]
    first_party_caveat = argv[2]

    m = macaroons.deserialize(serialized)
    V = macaroons.Verifier()
    V.satisfy_exact(first_party_caveat)
    try:
        print(V.verify(m, key))
    except Exception as e:
        print("False")
    exit(0)

if __name__ == "__main__":
    main(sys.argv[1:])
