#!/usr/bin/env python

# script arguments: serialized_macaroon discharge_macaroon key
#                   first_party_caveat discharge_first_party

import sys

import macaroons


def main(argv):
    serialized_macaroon = argv[0]
    discharge_macaroon = argv[1]
    key = argv[2]
    first_party_caveat = argv[3]
    discharge_first_party = argv[4]

    m = macaroons.deserialize(serialized_macaroon)
    dp = macaroons.deserialize(discharge_macaroon)

    # print(m.inspect())
    # print(dp.inspect())

    V = macaroons.Verifier()
    V.satisfy_exact(first_party_caveat)
    V.satisfy_exact(discharge_first_party)

    try:
        print(V.verify(m, key, [dp]))
    except Exception as e:
        print("False")

    exit(0)

if __name__ == "__main__":
    main(sys.argv[1:])
