#!/usr/bin/env node

// script arguments: location key id

var MacaroonsBuilder = require('macaroons.js').MacaroonsBuilder;

var location = process.argv[2];
var key = process.argv[3];
var identifier = process.argv[4];
var macaroon = MacaroonsBuilder.create(location, key, identifier);

console.log(macaroon.signature);
