#!/usr/bin/env node

// script arguments: location key id caveat_id

var MacaroonsBuilder = require('macaroons.js').MacaroonsBuilder;

var location = process.argv[2];
var key = process.argv[3];
var identifier = process.argv[4];
var caveat_id = process.argv[5];

var macaroon = new MacaroonsBuilder(location, key, identifier)
    .add_first_party_caveat(caveat_id)
    .getMacaroon();;

console.log(macaroon.serialize());
console.log(key);
console.log(caveat_id);
